### ISSUE TITLE
Error handling for wrong credentials

### ISSUE THREAD

**Issue by dm82m** [dm82m/hass-Deltasol-KM2#13]
After #12 is integrated we should improve the error handling. I want to handle wrong credentials next. KM2 is giving this result in case of bad credentials:

```json
[
    {
        "jsonrpc": "2.0",
        "id": "1",
        "error": {
            "category": "App",
            "message": "Invalid credentials"
        }
    }
]
```

What we need to know is, if the answer of a DL2/DL3 call is the same on bad credentials.

**Comment by chiefdeputy** [comment]
Calling ``http://my-dl2/dlx/download/live?sessionAuthUsername=admin&sessionAuthPassword=wrongpw`` gives me a 403 status including the html login form (no json).
