### ISSUE TITLE
Unexpected error fetching deltasol_km2_sensor data: Your device was reachable but we could not correctly detect it

### ISSUE THREAD

**Issue by TheBazeman** [dm82m/hass-Deltasol-KM2#17]
Hi, great work, but it seems not working for me, looks like http://192.168.55.162/cgi-bin/resol-webservice gives garbage: 
![afbeelding](https://user-images.githubusercontent.com/45493950/156768865-2ecbd964-ccfd-41b2-9dba-c18e7a8bfc18.png)

I can read data with ServiceCenter though and I can access the device without problems:
![afbeelding](https://user-images.githubusercontent.com/45493950/156769304-173e8086-c5ba-4408-afc1-ee5d1d317615.png)

Can you help me out?

Thanks,
Bas

**Comment by dm82m** [comment]
Can you please post all log Output That contains deltasol and please set your logging to debug first.

**Comment by chiefdeputy** [comment]
Do you have a "Resol VBus / LAN"  adapter? If so, those are not supported.
Only "Resol KM2", "Resol DL2" and "Resol DL3" as these devices collect bus data and provide them via Rest API.
VBus/Lan adapters are mere bus transceivers and do not have the needed functionality for this component.

**Comment by dm82m** [comment]
I had the same guess but raised a question to Daniel here: https://github.com/danielwippermann/resol-vbus/issues/73

**Comment by chiefdeputy** [comment]
Daniel provides a JSON server example in his JavaScript lib, which listens to Lan devices and "emulates" a KM" interface.
But this is way out of scope of this extension I guess.

**Comment by dm82m** [comment]
At least if you aren’t willing to implement that 🥳

**Comment by TheBazeman** [comment]
Hi all, yes I have an Resol VBus / LAN adapter. Allright I know enough ;-) Will have a look at Daniel his scripts

Thanks all,

regards,
Bas

**Comment by TheBazeman** [comment]
Hi Dirk,

Nice! I would like to, but I don't have a lot of time coming months and running HASS Core (with live-data-server and working like a charm through the configuration.yaml) and not HASS OS yet. Planning to get to HASS OS in a VM in a while. That's for me the moment to take a look at this again.

Thanks a lot,
Bas
