### ISSUE TITLE
Resol text missing

### ISSUE THREAD

**Issue by sla004** [dm82m/hass-Deltasol-KM2#2]
Hi,

Thanks for this great component. I tried many components but this was first I managed to get easily working. Maybe you should add resol text to somewhere that users would help this much easier?

**Comment by dm82m** [comment]
Happy that it works for you. Will add Resol as text in the next release.
What other plugins have you tested? I have not found anything else thus created my own.

**Comment by sla004** [comment]
At least these two. 
https://github.com/epenet/hassResolVbus
https://github.com/danielwippermann/resol-vbus

**Comment by dm82m** [comment]
> At least these two.
> https://github.com/epenet/hassResolVbus
> https://github.com/danielwippermann/resol-vbus

But these are not compatible with the KM2 network interface. They are for the vbus endpoint.
