### ISSUE TITLE
Support possible for VBus®/LAN interface adapter?

### ISSUE THREAD

**Issue by CaptInsano** [dm82m/hass-Deltasol-KM2#20]
I have the vbus adaptor here:

https://www.resol.de/en/produktdetail/76

Is it possible to access it's data via this integration? When I set up the integration at present I get the following error with debugging active:

`Unexpected error fetching deltasol_km2_sensor data: Your device was reachable but we could not correctly detect it`

I can access the vbus data over LAN via the RESOL Service Centre app:

![image](https://user-images.githubusercontent.com/332478/181093478-d46d1943-2993-4b34-a438-fe24b037047c.png)

The WebUI for the vbus to LAN adaptor looks like the following:

![image](https://user-images.githubusercontent.com/332478/181093842-39dd5221-3904-4df5-8d28-859f2a4e7714.png)

![image](https://user-images.githubusercontent.com/332478/181093950-4d796df6-0725-4293-8a30-6be3c41b498b.png)

I would gladly help in any way possible if we could get his working.

I would love to get the sensor data into homeassistant

**Comment by dm82m** [comment]
Sadly not supported, see: https://github.com/dm82m/hass-Deltasol-KM2/issues/17

**Comment by dm82m** [comment]
@CaptInsano I created an Home Assistant addon to run the json-live-data-server. Would you like to be a test candidate?
