### ISSUE TITLE
What is "Host, Username and Passwort"

### ISSUE THREAD

**Issue by MiSpri1974** [dm82m/hass-Deltasol-KM2#21]
sorry, but i just don't get it. What should be entered for host, username and password?  
No username is required to access the KM2 via IP address, only a password.  So when I enter the IP of the KM2 as the host, I'm missing the username. the access data from Vbus.net are also not accepted.  
Can someone help with what data I need to enter, please?

**Comment by dm82m** [comment]
Try admin as user

**Comment by dm82m** [comment]
See https://github.com/dm82m/hass-Deltasol-KM2/issues/18

**Comment by MiSpri1974** [comment]
wow, thanks for the incredibly quick response.  I would never have thought of "admin", but now it works.  Thank you very much.
