### ISSUE TITLE
0.3.1b1/0.3.1b2 Installationsfenster funktioniert nicht

### ISSUE THREAD

**Issue by hoppel118** [dm82m/hass-Deltasol-KM2#25]
Hi, habe gerade versucht das Update von 0.3.0b3 zu 0.3.1b1 durchzuführen.

Dabei ist folgendes passiert:

Der Ladekreis unten rechts hörte nicht auf zu laden:

![screenshot_1237](https://user-images.githubusercontent.com/991344/211020475-c9140a05-84c0-4079-aae2-50a6680c0713.png)

Nach ca. 15 Minuten habe ich den Updatevorgang abgebrochen, da das Update bei bisherigen Version innerhalb von 1-3 Minuten installiert war. Anschließend habe ich die Integration entfernt und wollte die Version einfach neu installieren. Gleiches Ergebnis, der Ladekreis unten rechts dreht sich "unendlich".

Also habe ich einfach ein zweites Fenster geöffnet und dann folgende Meldung entdeckt.

![screenshot_1238](https://user-images.githubusercontent.com/991344/211021506-800c849a-d6a4-4c80-a643-b7aa805f8bbf.png)

Die Installation scheint also schon fertig zu sein. Ich bin mir jetzt nicht sicher, ob das an deiner Integration liegen kann oder an dem HACS 1.29.1 Update gestern.

In der configuration.yaml habe ich die entsprechenden Änderungen von deltasol zu resol vorgenommen. Anschließend habe ich dann versucht den Neustart von Home Assistant durchzuführen. Bei der Konfigurationsprüfung habe ich dann allerdings folgende Meldung erhalten:

![screenshot_1239](https://user-images.githubusercontent.com/991344/211022456-da78901d-8e76-4099-b11c-6e68829cf32f.png)

Dann habe ich die gesamte deltasol config in der configuration.yaml einfach auskommentiert und HA neugestartet. Anschließend war die Integration nicht installiert. Also wollte ich den nächsten Versuch starten und habe dann festgestellt, dass es nun schon eine neue Version gibt:

![screenshot_1240](https://user-images.githubusercontent.com/991344/211023004-c871ac40-32f7-461f-95d0-5d05a8e37ada.png)

Vielleicht löst die ja dieses Problem. Also nochmal auf "Herunterladen" geklickt und eine knappe Stunde später immer noch der Ladekreis:

![screenshot_1241](https://user-images.githubusercontent.com/991344/211035079-81c93a04-241f-4fa1-aaab-192d05e62675.png)

Dann nächster Versuch, v0.3.0. "Herunterladen" angeklickt, BÄMM!!! 10 Sekunden später, Integration fertig installiert, kurz die configuration.yaml wieder von resol zu deltasol umgestellt, HA Neustart, läuft. Die Werte werden aktualisiert.

![screenshot_1242](https://user-images.githubusercontent.com/991344/211036390-fbae993b-235c-46ff-8b66-17976a453eb8.png)

Gruß Hoppel

**Comment by dm82m** [comment]
Nicht auf diese Versionen updaten, hab ich doch vorher sogar noch geschrieben. Vergiss diese Version und geh zur 0.3.0 zurück und bleib da bis es ggf mal wieder ein offizielles Update gibt.

**Comment by hoppel118** [comment]
Kein Ding, bin hier gerade am Arbeiten und habe das so nebenbei gemacht. Von deinem anderen Post hatte ich nichts mitbekommen. Wie dem auch sei, 0.3.0 läuft einwandfrei.
