### ISSUE TITLE
After update, KM2 no longer works

### ISSUE THREAD

**Issue by MiSpri1974** [dm82m/hass-Deltasol-KM2#26]
After update, KM2 no longer works, error message of all entities: "This entity is no longer provided by the deltasol integration. If the entity is no longer used, delete it in the settings."

**Comment by dm82m** [comment]
Guess you tried a beta? Please install 0.3.0 and all should be fine.

**Comment by MiSpri1974** [comment]
No, I updated to 0.3.0 and now it does not work anymore.

**Comment by dm82m** [comment]
Please post your sensor definition and the logs that contain deltasol and or resol.

**Comment by MiSpri1974** [comment]
strange, I have now restarted again to read the logs and now everything works. Sorry

**Comment by dm82m** [comment]
Great that it is back working.

**Comment by MiSpri1974** [comment]
Thank you for the quick support, great work
