### ISSUE TITLE
Sensors unavalaible since last update of HA core core_2023.2.2

### ISSUE THREAD

**Issue by hydro86** [dm82m/hass-Deltasol-KM2#28]
Sensors unavalaible since last update of HA core core_2023.2.2
![Unavailable](https://user-images.githubusercontent.com/47390591/219435675-0bce49c8-30ba-4c00-8f6a-d7a6aa30a55f.jpg)

**Comment by dm82m** [comment]
![1A35CA2F-5BE5-481B-9DC8-CCD127E6CCE4](https://user-images.githubusercontent.com/736311/219436233-9f4547a4-f108-41d5-b6ff-dc4b140a50f5.png)

Can’t confirm that on my side. Can you enable debug log and post it here?

**Comment by hydro86** [comment]
The main log?
Error detecting Resol product - HTTPConnectionPool(host='192.168.1.109', port=80): Max retries exceeded with url: /cgi-bin/get_resol_device_information (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa61d8520>, 'Connection to 192.168.1.109 timed out. (connect timeout=None)')), please file an issue at: https://github.com/dm82m/hass-Deltasol-KM2/issues/new/choose

**Comment by hydro86** [comment]
I still can access the KM2 with the webbrowser

**Comment by dm82m** [comment]
It’s a networking issue. Your home assistant host can’t reach your KM2. Try to ping that device directly from your home assistant host.

**Comment by hydro86** [comment]
I've rebooted so many times the Resol Module and the Home Assistant, the ping was always good but the integration not. And now by magic it works again but I don't know why. Anyway thanks your support

**Comment by dm82m** [comment]
Glad it works 🎸

**Comment by hydro86** [comment]
![Reavailable](https://user-images.githubusercontent.com/47390591/219455977-3f66c974-6ce0-44c4-a3ea-46e1cb15a65c.jpg)
