### ISSUE TITLE
Support Resol DLx devices

### ISSUE THREAD

**Issue by chiefdeputy** [dm82m/hass-Deltasol-KM2#3]
Hi,

thanks for sharing this custom component. Would you be open to make this component also work with the DL2/DL3 devices by Resol instead of only the KM2? (Which is out of stock in Germany till 2023 at least, or so I heard from a shop support.)
It's actually easier to get the data out of these devices. If you're interested, I can do a small PR in the next few days, to discuss. (Warning Python newbie 😅)

**Comment by dm82m** [comment]
Lets see what we can achieve. As I do not own an DL2/DL3 I can't test it and I have no idea what we need to do. The first question would be: how can we communicate between Home Assistant (python environment) with the DL2/DL3? With KM2 its quite easy cause it is available in the network as own network device.

**Comment by chiefdeputy** [comment]
I'm open for criticism for the PR. I could only test the "dlx" mode as I don't own a KM2.
