### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by lambertrutges** [dm82m/hass-Deltasol-KM2#35]
when I try to connect mij KM2 the following messages appears in the log:

homeassistant.exceptions.IntegrationError: Error detecting Resol product - HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.2.190/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f205cb4e4d0>: Failed to establish a new

Thanx for your help!!

**Comment by dm82m** [comment]
Please post your configuration.yaml (remove the password)

**Comment by lambertrutges** [comment]
sensor:
  - platform: deltasol
    host: http://192.168.2.190/#/
    username: admin
    password: your_password

**Comment by dm82m** [comment]
Change it to
`host: 192.168.2.190`

**Comment by lambertrutges** [comment]
Thanx it works now!
