### ISSUE TITLE
Meldung: Could not fetch changelog for a14d3924_resol-vbus

### ISSUE THREAD

**Issue by yahoogreg** [dm82m/hass-Deltasol-KM2#42]
Hallo Dirk,

zuerst möchte ich mich bei dir bedanken für das großartige Add-On das du hier entwickelt hast.
Das läuft bei mir seit letztes Jahr Februar (da habe ich mit Home Assistant angefangen) völlig problemlos.

Allerdings bekomme ich seit einigen Tagen **alle 5 Minuten** folgende diese folgenden beiden Meldungen im Log:

__Logger: homeassistant.components.hassio.data
Quelle: components/hassio/data.py:497
Integration: Home Assistant Supervisor ([Dokumentation](https://www.home-assistant.io/integrations/hassio), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
Erstmals aufgetreten: 15:26:20 (22 Vorkommnisse)
Zuletzt protokolliert: 17:06:54

Could not fetch changelog for a14d3924_resol-vbus:__

====================================

_Logger: homeassistant.components.hassio.handler
Quelle: components/hassio/handler.py:612
Integration: Home Assistant Supervisor ([Dokumentation](https://www.home-assistant.io/integrations/hassio), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
Erstmals aufgetreten: 15:26:20 (22 Vorkommnisse)
Zuletzt protokolliert: 17:06:54

Client error on /addons/a14d3924_resol-vbus/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/a14d3924_resol-vbus/changelog')_

Wenn ich bei dem Resol-VBus Add-On auf den Link "Änderungsprotokoll" drücke kommt ebenfalls die Warnung
Add-on Änderungsprotokoll konnte nicht abgerufen werden
No changelog found for add-on a14d3924_resol-vbus!

Das Ganze ist anscheinend nicht nur bei deinem Add-On so, denn in der Community haben ettliche andere das gleiche Problem mit ihren Add-On's.

Könntest du dir das bitte mal anschauen.

Danke und viele Grüße
Gregor

**Comment by yahoogreg** [comment]
Alles klar, vielen Dank für die schnelle Rückmeldung und Information.Am 07.05.24, 18:01 schrieb Dirk ***@***.***>:

   
  Das ist ein bug im supervisor von home assistant und in der 2024.5.0 gefixt. Musst noch warten bis das released ist oder du holst dir die Beta des supervisors wenn es dich zu arg stört. Siehe: home-assistant/supervisor#5064

**Comment by dm82m** [comment]
Supervisor 2024.05.01 ist released, Dein Problem sollte nach dem Update also weg sein!

**Comment by yahoogreg** [comment]
Stimmt, das Problem ist weg. Nochmals vielen Dank für deine Unterstützung.Am 08.05.24, 09:25 schrieb Dirk ***@***.***>:

   
  Supervisor 2024.05.01 ist released, Dein Problem sollte nach dem Update also weg sein!
