### ISSUE TITLE
Error while setting up deltasol platform for sensor

### ISSUE THREAD

**Issue by Steff6666** [dm82m/hass-Deltasol-KM2#5]
Hi,

Thanks for your this custom component, I really hope I can get it to work.
 
Installed from HACS and got two (2) errors after restart and can not get it to work. 

Logs say...

Error 1:
Logger: homeassistant.components.sensor
Source: custom_components/deltasol/sensor.py:73 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 00:41:49 (1 occurrences) 
Last logged: 00:41:49

Error while setting up deltasol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/deltasol/sensor.py", line 73, in async_setup_platform
    DeltasolSensor(coordinator, _name, values[1], values[2]) for _name, values in coordinator.data.items()
AttributeError: 'NoneType' object has no attribute 'items'

Error 2:
Logger: custom_component.deltasol
Source: custom_components/deltasol/deltasolapi.py:33 
Integration: deltasol ([documentation](https://github.com/dm82m/hass-deltasol-KM2), [issues](https://github.com/dm82m/hass-deltasol-KM2/issues)) 
First occurred: 00:41:49 (1 occurrences) 
Last logged: 00:41:49

Unexpected error fetching deltasol_km2_sensor data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/deltasol/sensor.py", line 54, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deltasol/deltasolapi.py", line 33, in fetch_data
    response = requests.request("POST", url, headers=headers, data = payload).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

yaml file:

sensor:
   - platform: deltasol
     host: 192.168.1.124
     username: admin
     password: !secret deltasol
     scan_interval: 00:05

**Comment by dm82m** [comment]
Format of scan_interval is wrong: it should be only a number in seconds. Change that and restart.

**Comment by Steff6666** [comment]
I changed it to just a number 30, ...and restarted but still getting same errors. Even tried to remove it , but both errors are the same and no sensors are found.

**Comment by dm82m** [comment]
Can you put that into your browser and post me the results: http://192.168.1.124/cgi-bin/resol-webservice

**Comment by Steff6666** [comment]
vendor = "RESOL"
product = "DL2"
serial = "001E664234FC"
version = "2.2.4"
build = "201909120704"
name = "DL2-001E664234FC"
features = "vbus,dl2,jobparam"

**Comment by dm82m** [comment]
You have a DL2 and no KM2 so this plugin is not yet suiting your needs.

**Comment by dm82m** [comment]
But you can have a look here and test it out and tell us if that works: https://github.com/dm82m/hass-Deltasol-KM2/issues/3

**Comment by Steff6666** [comment]
Thanks for your support! I tried to find out how to copy the two files, but so far I have not managed. I can open the files and copy the content and then paste it in new files...but the formatting and lines are not copied correctly. Im a newbie to this and appreciate all help a lot, thanks!

**Comment by dm82m** [comment]
you can copy the content of both files from the following links and need to replace the content with them in your home assistant folder. after that you need to put mode: dlx into the sensor definition (equal to host). it should look like:

https://raw.githubusercontent.com/dm82m/hass-Deltasol-KM2/7f52cf6d9810aa266150b12bbf6b8d6de0e88c59/custom_components/deltasol/deltasolapi.py
https://raw.githubusercontent.com/dm82m/hass-Deltasol-KM2/7f52cf6d9810aa266150b12bbf6b8d6de0e88c59/custom_components/deltasol/sensor.py

```
sensor:
  - platform: deltasol
    host: your_deltasol_hostname_or_ip_address
    username: your_username
    password: your_password
    mode: dlx
```

**Comment by Steff6666** [comment]
Im getting this error now
Invalid config for [sensor.deltasol]: [mode] is an invalid option for [sensor.deltasol]. Check: sensor.deltasol->mode. (See ?, line ?).

I added the raw text in existing files in HA and attach them here, I hope they are correct.

[Deltasol.zip](https://github.com/dm82m/hass-Deltasol-KM2/files/8010067/Deltasol.zip)

**Comment by dm82m** [comment]
ah sorry, it is api_mode not mode. changed it above in my last post

**Comment by Steff6666** [comment]
its changed , but still error
Invalid config for [sensor.deltasol]: [api_mode] is an invalid option for [sensor.deltasol]. Check: sensor.deltasol->api_mode. (See ?, line ?).

**Comment by dm82m** [comment]
@chiefdeputy can you have a look here.

**Comment by Steff6666** [comment]
No its not restarted yet...I was thinking the same that this could be the reason. The reason was that it was not possible to restart because the yaml file was invalid. I will ignore the "mode" to get a valid config file->restart-> put mode back....give me some minutes

**Comment by dm82m** [comment]
Yes, without a restart it can’t work. Leave mode away, restart, add mode: dlx and restart again

**Comment by Steff6666** [comment]
I´m having issues with HA, because of the sensor.py file. The validation of yaml file is not possible. When I try to restart It say (unicode error) utf-8´codec can't decode byte 0xb0 in position 0: invalid start byte (sensor.py, line 145). Maybe the .py files are not correct after my updates?

**Comment by Steff6666** [comment]
It was the degree symbol that cause the problem. Just removed it and now configuration is fine. Restarted HA -> put mode: dlx in -> checked configuration and it was fine -> restarted. No errors in logs now!

Next step is to find sensors...but can not find any Deltasol sensors so far...

**Comment by Steff6666** [comment]
YES!! I found the sensors now. They are named just sensor.temperature etc with any "DeltaSol" in the name...is that correct?
<img width="490" alt="Skärmavbild 2022-02-06 kl  13 54 10" src="https://user-images.githubusercontent.com/88351415/152681768-29c2f11a-e4f8-4cab-8125-23315eaa4fe2.png">
<img width="499" alt="Skärmavbild 2022-02-06 kl  13 53 46" src="https://user-images.githubusercontent.com/88351415/152681773-b352ad7f-07de-4778-b08d-8d6617c09c4f.png">

**Comment by dm82m** [comment]
yes thats it, I am just releasing a new official version so you can update the plugin in a few minutes.

**Comment by Steff6666** [comment]
Great! How to do with Unicode '°C' ? HA stopped working for me because of this degree symbol.

**Comment by dm82m** [comment]
release is out, can you please upgrade to 0.1.0 and tell me if this also solves your unicode problem?

**Comment by dm82m** [comment]
I close here. In case there is a Unicode issue please file a new bug!

**Comment by Steff6666** [comment]
Just upgraded and all works fine and no problem with unicode. Thanks!
