### ISSUE TITLE
Adding API filter paramater 

### ISSUE THREAD

**Issue by ostat** [dm82m/hass-Deltasol-KM2#7]
Thanks for adding the DLX support. 

The DLX API supports creating filters on the DL2/3, that allow for customising the names of the sensors. This should allow them to show in HA with detailed naming. I wanted to extend the integration with an additional config for providing a filter number so as to leverage this feature. 

Matching the changes made for DLX addition. I added `CONF_FILTER` to `homeassistant.const`, and added `vol.Optional(CONF_FILTER): config_validation.string` to the `PLATFORM_SCHEMA`, as well some some changes to the deltasolapi.

I am now getting an error `ImportError: cannot import name 'CONF_FILTER' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`
Do I need to do something to register the new config?

TIA

**Comment by dm82m** [comment]
Please provide a pull request so that we can have a look. Code debugging depending on comments is nearly impossible.

**Comment by ostat** [comment]
PR created #8

**Comment by dm82m** [comment]
your stuff is integrated and slighty modified. will release it in a couple of minutes. thanks for contributing!
